// Code generated by ent, DO NOT EDIT.

package ent

import (
	"order/ent/order"
	"order/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	orderFields := schema.Order{}.Fields()
	_ = orderFields
	// orderDescIsDeleted is the schema descriptor for is_deleted field.
	orderDescIsDeleted := orderFields[9].Descriptor()
	// order.DefaultIsDeleted holds the default value on creation for the is_deleted field.
	order.DefaultIsDeleted = orderDescIsDeleted.Default.(bool)
}
